version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - "> 3.12.12"
  - dependency-name: com.squareup.okhttp3:okhttp-urlconnection
    versions:
    - "> 3.12.12"
  - dependency-name: com.squareup.retrofit2:converter-simplexml
    versions:
    - "> 2.6.0"
  - dependency-name: com.squareup.retrofit2:retrofit
    versions:
    - "> 2.6.0"
